stages:
  - sync

sync_version:
  stage: sync
  tags:
    - windows
  only:
    - dev
  script:
    - git config --global user.name "gitlab-ci"
    - git config --global user.email "gitlab-ci@example.com"
    - git clone https://oauth2:${DEMO_SYNC_TOKEN}@gitlab.com/<your-user-or-group>/demo-target.git demo-target
    - git -C demo-target checkout dev
    - powershell -ExecutionPolicy Bypass -File .\scripts\sync-common-package-version.ps1 -WorkspaceRoot $CI_PROJECT_DIR -Branch dev